/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
// Note: .astro/icon.d.ts is only generated by `astro build`/`astro dev` (not `astro sync`).
// We declare `virtual:astro-icon` statically here so `astro check` works without a prior build.

// `interface` is required here (not `type`) — these augment the ambient
// `ImportMetaEnv`/`Window` globals via TypeScript declaration merging, which
// only works with `interface`. See the `**/*.d.ts` oxlint override.
interface ImportMetaEnv {
  /** Opt in to recording Answer events while running the dev server. Prod always records. */
  readonly PUBLIC_RECORD_ANSWERS?: string
}

interface Window {
  langsModal: HTMLDialogElement
  posthog?: import('posthog-js').PostHog
}

// No @types packages exist for these modules (both used by src/server/card-image.ts);
// declare them to suppress ts(7016).
declare module 'bidi-js' {
  const bidiFactory: () => {
    getEmbeddingLevels(text: string, dir?: 'ltr' | 'rtl'): unknown
    getReorderedString(text: string, levels: unknown): string
  }
  export default bidiFactory
}

declare module 'wawoff2' {
  export function decompress(buf: Uint8Array | Buffer): Promise<Uint8Array>
}

// Static fallback for virtual:astro-icon — the full icon-name union is generated into
// .astro/icon.d.ts only during `astro build`/`astro dev`, not during `astro sync` / `astro check`.
// Using `string` here keeps the type broad but suppresses the "cannot find module" error.
// At build time the richer generated union takes precedence via Vite's virtual module resolution.
declare module 'virtual:astro-icon' {
  export type Icon = string
}
