import {env} from '~env'

export const ANDROID_TESTER_GROUP_URL = env.ANDROID_TESTER_GROUP_URL
export const ANDROID_TESTER_OPT_IN_URL = env.ANDROID_TESTER_OPT_IN_URL
export const ANDROID_TESTER_FEEDBACK_URL = env.ANDROID_TESTER_FEEDBACK_URL ?? '/contact'

export const ANDROID_TESTER_LINKS_READY = Boolean(
  ANDROID_TESTER_GROUP_URL && ANDROID_TESTER_OPT_IN_URL
)
